# -*- coding: utf-8 -*-
"""Face_detection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sPt0HsSqw7V4k-256aRqPWv1cNv1qmC-
"""

import cv2
#Import the necessary patch for displaying images in colab
from google.colab.patches import cv2_imshow

class FaceDetection:
    def __init__(self):
        self.face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')

        def detect_faces(self, image_path):
            image = cv2.imread(image_path)
            if image is None:
                print(f"Error:could not read image from {image_path}")
                return #Exit the function if image loading failed

            gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)
            #Detect faces
            faces = self.face_cascade.detectMultiScale(gray,scaleFactor= 1.1,minNeighbors=5,minsize=(30,30))
            #Draw rectangles around detected faces
            for(x,y,w,h) in faces:
                cv2.rectangle(image,(x,y),(x+w,y+h),(255,0,0),2)

            cv2_imshow(image)
            cv2.waitKey(0)
            cv2.destroyAllWindows()
if __name__ =="_main_":
    detector = FaceDetection()

detector.detect_faces("Face_Sample.jpg")

